# Set to true to add reviewers to pull requests
addReviewers: true

# AssigneeをPR作成者自身に設定
addAssignees: author

# GitHubのユーザ名でレビュワーを設定
reviewers:
  - shun198

# レビュワーをグループ別に分ける
# reviewGroups:
#   groupA:
#     - reviewerA
#     - reviewerB
#     - reviewerC
#   groupB:
#     - reviewerD
#     - reviewerE
#     - reviewerF
