name: Auto Assign Assignee and Reviewer

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  review:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-20.04
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
