name: Auto Assign Assignee and Reviewer

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  review:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-20.04
    steps:
      - name: Auto Assign Assignee and Reviewer
        uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Add Labels to Pull Request
        uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Print Title of PR
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}
      - name: Check word that contains in pr title
        uses: actions-ecosystem/action-add-labels@v1
        if: contains((github.event.pull_request.title,"GitHub Actions")
        # run: echo PR contains ${{ github.event.pull_request.title }}
        with:
          labels:
            ci/cd
