name: Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  review:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-20.04
    steps:
      - name: Auto Assign Reviewer
        run: gh pr create --fill --reviewer shun198
        env:
          GH_TOKEN: ${{ github.token }}
